### ISSUE TITLE
three-vrm-girl.vrm doesn't support lookUp/Down/Left/Right with blendshape

### ISSUE THREAD

**Issue by BrandonHanx** [pixiv/three-vrm#471]
Hi all, thx for this work.
I found the `lookUp/Down/Left/Right`  in `VRMBlendShapeProxy` doesn't work with three-vrm-girl.vrm.
I know I can use `LookAt` to solve this problem in another way, however, I found the model doesn't bind on this bone (i.e., `vrm.blendShapeProxy._blendShapeGroups.LookUp._binds=[]`). 
I wonder whether there are some error happened with model's initialization or not.
Thanks in advance!

**Comment by FMS-Cat** [comment]
If you need to move eyes of characters, you should use LookAt instead, as you have mentioned.

In vrm, author can choose either bones or blendshapes for LookAt.
And the interface of LookAt enables us to use their eye movement in either way (end dev doesn't need to know about how they are implemented).
`three-vrm-girl.vrm` uses bones for lookAt feature instead of blendshapes.
i.e. you should not use `LookUp` , `LookLeft` ... directly from `blendShapeProxy`, you should use the interface of `lookAt` instead.

Does this make sense? / Is there any problem with `lookAt` ? Do you still have a reason that you have to use `blendShapeProxy` ?

**Comment by BrandonHanx** [comment]
Thanks for your reply. 

This makes sense, and can I understand that whether a VRM model's eye supports blendshape or not is already determined when it is built?

My original intention was to control the gaze movement of VRM through a deep learning model. Since the output of deep learning model is landmark, it may be more convenient to use blendshape to do this. It seems that I have to use lookAt now :<

**Comment by FMS-Cat** [comment]
Aha got it. I think you can use `LookAtHead.applyer.lookAt(Euler)` instead? With this you can manually set the angle.
It receives an euler angle. x and y components are being used.
Make sure you're setting `LookAtHead.autoUpdate = false` before use this.

**Comment by BrandonHanx** [comment]
Sorry for late reply. This works fine for me. Thanks again!
